name: Run Cucumber Tests and Update Report

on:
  workflow_dispatch:

jobs:
  run-cucumber:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'

      - uses: browser-actions/setup-chrome@latest
      - name: Run Cucumber Tests
        run: mvn clean test

      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.REPORT_GEN }}
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Update Cucumber Report"
          git push
